version: "3.8"

services:
  rabbitmq-go:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-go
    ports:
      - 5672:5672      # Rabbits default port
      - 15672:15672    # Management UI port
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 5672 || exit 1"]
      interval: 5s
      start_period: 30s

volumes:
  rabbitmq-go: